# Breakdown of barriers {#barriers-breakdown}

::: {.alert .alert-secondary}
 

Other authors have given related decompositions; see, e.g., [@caviolaPsychologyEffectiveAltruism2021] and [@jaegerPsychologicalBarriersEffective2021]. We provide some comparisons below; these outlines are separately discussed presented [above](#effectiveness-prev-work).

 
:::

## Breakdown of 'barriers' (first presentation) {#barriers-concept}

We focus on the 'barriers' or 'hurdles to giving effectively' among individuals who *already* engage in some charitable giving and other-regarding acts.\* Loosely, a donor would need to "jump over all of these hurdles" in order to make it to 'giving effectively'.\*\*

::: marginnote
\* We do not focus on other barriers to 'generous intentions or actions' in general.

\*\* Consider: is there a well-known psychological framework for these sorts of multiple-hurdle choices?
:::

::: marginnote
Later chapters present the direct and indirect evidence for very specific barriers, with real-world examples, and proposed 'tools' for surmounting these. In doing this, the conceptual breakdown proved difficult, as most of the real-world cases fell into multiple theoretical categories.
:::

We began by thinking about a fairly *conceptual* breakdown:

::: {.alert .alert-secondary}
 

**A conceptual breakdown of barriers:**
  
  
*Values:*
  
Base values may be (non) utilitarian: People are optimising their own 'X', which does not coincide with impact $\rightarrow$ no puzzle? We discuss this, and consider the 'evidence', to the extent this is possible, in the (WIP) section [Do people actually care about impact? Does moral utilitarianism matter?](#doesimpactmatter). 
 

\

*Effectiveness, judgement and cognition limitations:*


- Avoiding information about effectiveness: Even if people want to optimise impact, they may specifically dislike and avoid gathering information about effectiveness in a charitable giving setting

- Presenting effectiveness information may backfire: E.g., if it switches off the 'generous part of the brain', gets people to think in a more 'market' mode, or makes people indecisive

- Judgement/cognition failures, quantitative biases, information failure: People try but fail to optimize, and/or have [persistent incorrect beliefs](#factual)

\


*Other internal factors and motivations:*
  
- Emotion overrides cognition: Our brain serves two masters, those decisions are not consistent

- Identity and signalling: Effectiveness in giving clashes with our self-image/self-beliefs, or with how we want to appear to others

- Limited moral circles, 'distance' to individuals and causes in need

\

*External factors:*

- Systemic factors (and inertia): "It's society's fault, man" ... social systems leading to pressure and incentives from others to give to local or less-effective causes. Even if impact is a goal, these systems take a long time to adjust.

 
:::

## "Practical breakdown (organizing this resource) {#barriers-practical}

Most of this bookdown is devoted to classifying potential barriers to effective giving and assessing the general and specific evidence for these barriers. We use a *practical* breakdown to organize this, particularly trying to avoid overlap between sections.

### Fundamental values, moral circles, awareness, identity, and signaling {.unnumbered}

A range of barriers could be considered in terms of the individual's fundamental values, how she perceives the universe and her obligations to it, and her desire to project a positive image to herself and others.

\

[**Non-utilitarian motivations**](#doesimpactmatter): Before considering each 'barrier to effective giving', we first consider the case (and evidence, as far as this is possible) that donation choices may be fundamentally driven by factors other than a "universalist cause-neutral 'desire to help others'.

\

[**Barriers: "Distance", awareness, and consideration, and consideration**](#aware-distance): People may tend to give more to a cause/charity that they are more aware of, that they feel is more important and salient, and that they feel close to. Some causes will be *closer* to the mass of potential donors than others; this can include physical closeness, cultural proximity, and more. As a result, other causes may be relatively neglected. This relates to "moral circle expansion" as well as quantitative biases such as the "availability heuristic".

Less proximate needs are less salient, thus they may be under-funded.

::: marginnote
Possible responses: Provide information or use other tools to enhance the social closeness of a recipient or beneficiary.
:::

\

\@ref(identity)**: [Barriers: Identity and cognitive dissonance](#identity)**

<!-- (This section needs more definition) -->

When presented with information that contradicts their own views, an individual may feel that their identity is being threatened and become even more committed to their original beliefs. They may be concerned that giving up their initial position will negatively affect their reputation. In the case of effective giving, someone may be unwilling to give effectively as they would have to acknowledge that the money they were donating before was, indeed, ineffective.\*

::: marginnote
\* Source: paraphrase from EA forum (specify, potentially replace with a more authoritative source)
:::

\

[**Signaling and social pressures/social identity**](#social)

Considering effectiveness in giving (and publicizing this concern) may conflict with an individual's self-perception. It may also harm her reputation, at least relative to emotional or 'deontological' helping responses.

<!-- Volunteer experience unlocks emotion and giving -->

```{=html}
-   social obligations to give locally (and 'crowding out'/moral licencing) (see, e.g., [@meerBrotherCanYou2011])

Does one contribution crowd out another? If so, social pressure, systems enforcing 'local public goods' and inertial factors may limit effective (non-local) giving.
```
```{=html}
<!-- #TODO: At some point we should make the point that in order for people to give effectively they need to know which charities are effective. For this to be the case, charities must transparently submit to rigorous metrics. Charities must advertise their impact and compete on this basis. For charities to want to do this, they must believe that donors as ‘consumers’ care about this.

According to Mulesky (2020) “Charities routinely appeal to impact when soliciting donations”; However, the example she gives is not a clear measure of per dollar impact.

However, a feature of philanthropy overlooked in published research is that nonprofit organizations rarely, if ever, support these claims with rigorous evidence
-->
```
```{=html}
<!--
(Yoruk, 2016), (Gneezy ea, '14)
yoruk_2016, Gneezy2014  brown_etal_2016, Chhaochharia_Ghosh_08?, Kinsbergen_tolsma_13
-->
```
\

### Effectiveness information: Avoidance, motivated reasoning, conflicts between analytic and empathetic modes {.unnumbered}

Even if people *want* to give effectively (and are not parochial, have wide moral circles, etc)...

... for people to give effectively they need to *know* which charities are effective.\*

::: marginnote
\*For this to be the case, charities must transparently submit to rigorous metrics. Charities must advertise their impact and compete on this basis. For charities to want to do this, they must believe that donors as 'consumers' care about this.

According to Mulesky (2020) "Charities routinely appeal to impact when soliciting donations"; However, the example she gives is not a clear measure of per dollar impact.

However, a feature of philanthropy overlooked in published research is that nonprofit organizations rarely support these claims with rigorous evidence.
:::

[**Evaluation-aversion and obstacles to considering charity impact**](#eval-aversion)

People may dislike doing this 'cost-benefit evaluation' in the context of charities, or may feel it is not appropriate. They may thus avoid doing it (see ['Cost-benefit analysis aversion'](#cba-aversion))

\

[**Effect of analytical (effectiveness) information on generosity**](#analytical-grinch)

Furthermore, doing, and being exposed to such evaluations may 'switch off' their empathy, or enable 'motivated reasoning' in considering this information, giving them 'excuses' to be less generous.\
In a more general sense, it may be that *emotion overrides cognition*.

\

### Judgement/cognition failures, systematic misperceptions {.unnumbered}

[**Barriers: Quantitative biases**](#quant-biases)**:** Biases in perceiving impact and in making choices

People may (at least to some extent) *want* to be effective in their donation. However, they may simply not be good at doing this. Quantitative biases may drive departures from effectiveness in general. Anything that causes me to misunderstand effectiveness, to misapprehend the nature of the "production function for good outcomes", or to misjudge charities will lead me astray from effective giving. If I am making any mistake, I am failing to optimize. Furthermore, some biases may happen to be *particularly* harmful to those charities and causes that are most effective.

::: marginnote
Cognitive biases include: Overweighting and underweighting probabilities, Misunderstanding marginality, Scope-insensitivity, Opportunity-cost Neglect, Identifiable victims effect, and Overhead aversion
:::

[**Barriers: Persistent and systematic incorrect empirical beliefs**](#factual)

In the absence of cost-effectiveness information, people may be systematically misinformed about which charities, interventions, and approaches are effective.

```{=html}
<!-- Responses: De-biasing, etc.

smallSympathyCallousnessImpact2007, gneezyAvoidingOverheadAversion2014, ein2013giving, kogut2005identified, kogut_2005b, Kinsbergen_tolsma_13 -->
```
<!-- (or excuse-driven, motivated reasoning), lack of tangibility (giving to a diffuse cause); Percieved lack of transparency, and perceived corruption overseas -->

```{=html}
<!-- Information about recipients' deservingness, Avoid uncertainties/excuses not to give/mental transactions costs
 (Fong & O, '10), (Exley, '16b) (Andreoni ea, '17), (Dellavigna ea, '12) -->
```
\

**Notes on previous sections ([Are Charities in Competition](#substitution), [Inertia](#inertia)) (unfold)**

::: {.foldable} 
 

In a previous sections we presented a [long discussion of the evidence and theory](#substitution) on whether 'one contribution comes at the expense of another', 
  
In an [appendix chapter](#inertia) we give a short (and incomplete/WIP) discussion of the issue of 'inertia', and whether slow changes in social norms and individual behavior are inhibiting effective giving. 

We do not present these explicitly as 'barriers'. To us, these seem like underlying factors that will *interact* with these barriers and make some things more or less salient. The nature of the evidence is also somewhat distinct. However, this is very much a judgement call, and we could have gone either way. It was also a judgement call to put the [discussion of underlying (non)-utilitarian values](#are_we_util) in the 'barriers' section. 

 
:::

