# INTRODUCTION & FUNDAMENTALS {-}


::: {.alert .alert-secondary}
 
In this set of chapters:

- What is this project about and how is it organised, outline of chapters
- What is the main question or 'puzzle' and how do we know it 'real' and important?
- Fundamental question: are charities in competition
- How do we *consider* 'barriers' and analyse the evidence (and organize this?)

 
:::

## Outline of key 'PARTS' (unfold) {-}

**INTRODUCTION & FUNDAMENTALS**


::: {.foldable} 
 

- [Presenting the puzzle and challenge: Our ineffective giving](#present-puzzle)**  Why should you care about this? Descriptives of giving (US, international) and how 'ineffective' it is. Potential global welfare gains to changing 'where we give'. Lack of previous evidence/synthesis

-  [Definitions - "Efficiency" versus impact](#impact-definitions)\

[Are charities in competition?](#substitution)


\

- [Breakdown of Barriers](#barriers-breakdown)


<!-- moved old classification to barriers_old_classification.Rmd -->
ve a general ['conceptual' overview of these barriers](#barriers-concept). We dig into each barrier more carefully in subsequent chapters.

\

Briefly mapping and outlining this...

-   Do people *actually care about* impact? Does moral utilitarianism matter?

-   Economics and psych models $\rightarrow$ puzzle?

-   Models where people care about the impact of their gift or just 'amount sacrificed' (naive warm glow).

-   Does impact map into the 'good feeling' from giving, can it do so?


 
:::

\

**BARRIERS...**

These parts clarify and operationalize each of the defined barriers (in sections), and assess the evidence (and argument) for each of these.


\

**GOING FORWARD...**

Here we consider 'tools' for surmounting these barriers, and flesh out a research agenda.
This is followed by appendices, including [one explaining the tech](#bookdown-appendix) behind this project, and how to work with it/work with us.


# Evidence, empirical considerations, organization {#evidence}

## Structure of each 'barriers' section {#structure-barriers}

**In each 'barriers' section we consider...**

1. **A category of barriers**; this is a first-level heading, e.g. '[Quantitative biases](#quant-biases)' is section \@ref(quant-biases).

Here we discuss this category in general, explaining its meaning and plausibility in terms of the underlying theories, models, and generalized observations.

2. **Each specific barrier in this category** gets a second-level heading, e.g., ["Proportional dominance effect"](#prop-dom) is section \@ref(prop-dom).


3. For each specific barrier we first present (third-level headings):

-   **Definition** of the barrier
-   **Conceptual explanation of the barrier**, relating this to theory and generalized observation
-   **Relevance to effective giving** (sometimes recapping what was stated above)

\
4. Next we consider the **Evidence**, with a third-level header preamble discussing the nature of the evidence.

5. Within this, we consider the **evidence for each specific empirical claim** supporting the case for this barrier's existence and importance.


::: {.alert .alert-secondary}
 

We hope to:

- 'operationalize' each claim with a falsifiable set of predictions
   - justifying the connection to each prediction,

- and carefully asses the strength of the evidence for each of these claims.

See, e.g., our work-in-progress on 'CBA avoidance' [here](#cba-evidence).

This distinguishes the current project from broader reviews and literature surveys.

 
:::

\

In considering the evidence for these claims, we generally consider one paper or project at a time (or a specific piece of independent evidence from this paper).^[ However, we are still considering the best narrative approach to presenting evidence from multiple papers/projects/analyses.
]

## Consideration of each paper {#paper-structure}

For each paper we focus on key elements, including:

-   **Method** (lab experiment involving real charitable asks, natural field experiment with charity partner, observational analysis asserting causality via a regression discontinuity approach, etc.)

-   The **context** and data (the population of donors or lab participants, the charity(s) involved, etc.)

-   The **nature of the 'treatment'** or independent variable (e.g., realistic information presented about impact per dollar)

-   The **strength and credibility of the empirical results** (considering, e.g., limitations and confounds in the design, experimenter-demand effects, estimates' statistical strength and power, appropriateness of the statistical analysis, preregistration, signs of specification-fishing and multiple-testing without corrections, replications and citations, etc.)

- Link where to find the paper itself as well as the materials and the data collected.\

::: {.alert .alert-secondary}
 
For example, within the category **[Barriers: Aversion/obstacles to *doing* (using) evaluations; effect of analytical information on generosity](#eval-aversion)** ...

we consider the barrier ["General cost-benefit analysis (CBA)-aversion or reluctance"](#cba-aversion)...

weighing evidence  specific claims such as ["People sometimes actively avoid information about charity effectiveness that would motivate doing a CBA..."](-#avoid_info_CBA)...


coming from research papers/studies such as  @fongTruthGivingExperimental2010.

 
:::

## Evidence and meta-analysis: discussion {#evidence0meta}


We consider^[Further discussion needed here
]


1. The nature of evidence for drivers of effective/ineffective giving, and how we might evaluate it

2. Meta analysis: Existing work and plans for doing meta-analysis as part of this project

See [innovationsinfundraising](https://innovationsinfundraising.org/doku.php?id=tools:meta-analysis_approach#references_and_discussion_of_specific_issues_in_meta-analysis) for some earlier discussion of this, as well as ["What works to increase charitable donations? A meta-review with meta-meta-analysis" by Noetel et al](https://psyarxiv.com/yxmva/)



## Airtable organisation; contributing content {#airtable-contrib}

**These classifications of barriers** are organised, outlined, and defined in our Airtable; see the view below.

<iframe class="airtable-embed" src="https://airtable.com/embed/shr7Hs75V0k24wtI9?backgroundColor=purple&amp;viewControls=on" frameborder="0" onmousewheel width="100%" height="330" style="background: transparent; border: 1px solid #ccc;">

</iframe>

\

**The barriers themselves** are organised as well, see the view below:

<iframe class="airtable-embed" src="https://airtable.com/embed/shrUbA0AdoQNymoCU?backgroundColor=purple&amp;viewControls=on" frameborder="0" onmousewheel width="100%" height="330" style="background: transparent; border: 1px solid #ccc;">

</iframe>

\

**To suggest a new barrier,** or a modification of an existing proposed barrier, please fill out the form below [and linked here](https://airtable.com/embed/shr1i7JKagMxTIXR8?backgroundColor=purple) (or contact us otherwise, including via a hypothes.is comment):

<iframe class="airtable-embed" src="https://airtable.com/embed/shr1i7JKagMxTIXR8?backgroundColor=purple" frameborder="0" onmousewheel width="100%" height="330" style="background: transparent; border: 1px solid #ccc;">

</iframe>


You can also engage in this project directly, helping us build this content in R/markdown or in a Google docs integration. See the ['tech for creating...' appendix](#bookdown-appendix).
\

**Did we leave out a paper or a source of evidence?** Please fill out the form below or [click the link HERE](https://airtable.com/embed/shr0fMY4izZX6Z0Hz?backgroundColor=purple) (or contact us otherwise, including via a hypothes.is comment):

\

<iframe class="airtable-embed" src="https://airtable.com/embed/shr0fMY4izZX6Z0Hz?backgroundColor=purple" frameborder="0" onmousewheel width="100%" height="400" style="background: transparent; border: 1px solid #ccc;">

</iframe>

**All contributions will be credited and engaged with.**

\

## Other practical considerations, partnerships


This project is informally connected with the [EA Market Testing team](https://effective-giving-marketing.gitbook.io/untitled/). However, this project is several years older, and the scope is not entirely overlapping. The present project focuses on giving, while EAMT has a broader agenda connected with the EA movement. The EAMT is mainly a practically-driven project, while the current synthesis also considers braoder and more theoretical issues.

\


Consider potential integration with...

::: {.foldable} 
 

Consider potential integration with (no-longer-maintained) PriorityWiki/Rethink Charity {-}

How have EA orgs been brought together ...especially at universities?

-   [Effective thesis project](https://effectivethesis.org/project/)

-   [EA hub](https://eahub.org/)

-   [Facebook group](https://www.facebook.com/groups/effective.altruists/)

 
:::

<html>

<!-- Global site tag (gtag.js) - Google Analytics -->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-148137970-4"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-148137970-4');
</script>
```
</html>

