project:
  type: book
  output-dir: docs

book:
  title: "Increasing effective giving (& action): The puzzle, what we (need to) know"
  author: "David Reinstein, Nick Fitz, Ari Kagan, Janek Kretschmer, Luke Arundel and others. Comments and contributions from Jason Schukraft, Michael Aird, Robin Bergh, Michel Justen, Annabel Rayner, and others"
  repo-url: https://github.com/daaronr/ea_giving_barriers
  repo-actions: [edit, issue]
  date: today
  chapters:
    - index.qmd
    - part: chapters/introduction.qmd
      chapters:
        - chapters/outline_work.qmd
        - chapters/present_puzzle.qmd
        - chapters/substitution.qmd
    - part: "BARRIERS"
      chapters:
        - chapters/barriers_breakdown.qmd
        - chapters/doesimpactmatter.qmd
        - chapters/BARRIERS_FUNDAMENTAL.md
        - chapters/aware-distance.qmd
        - chapters/identity.qmd
        - chapters/social.qmd
        - chapters/BARRIERS_INFO.md
        - chapters/eval-aversion.qmd
        - chapters/impact_analytical.qmd
        - chapters/BARRIERS_JUDGEMENT.md
        - chapters/quant-biases.qmd
        - chapters/factual.qmd
    - part: "PATHS FORWARD"
      chapters:
        - chapters/tools.qmd
        - chapters/conclusion-agenda.qmd
    - chapters/references.qmd
  appendices:
    - chapters/appendix_tutorial.qmd
    - chapters/inertia.qmd
  reader-mode: true

comments:
    hypothesis: true

bibliography: [references.bib, reinstein_bibtex.bib, packages.bib]

format:
  html:
    #code-fold: true
    #code-link: true #note: this isn't working for me
    #code-tools: true
    theme: cosmo
    citations-hover: true
    footnotes-hover: true
 # pdf:
  #  documentclass: scrreprt

#editor: visual

