###  Barriers: Biases in perceiving impact

**NOTE: this classification proved to be difficult in practice, as there was too much overlap! Move to the more 'practical' classification in the other doc.'**

Cognitive biases: Overweighting and underweighting probabilities, misunderstanding marginality, scope-insensitivity, Opportunity-cost Neglect. etc. Identifiable victims effect. Responses: De-biasing, etc.

small2007sympathy, Gneezy2014	ein2013giving, kogut2005identified, kogut_2005b, Kinsbergen_tolsma_13


### Barriers: Presenting analytical/impact information switches off system 1;

Charity effectiveness (info/deliberation) -, Donor's mood (Impacting) - Affect prime -, Evaluation mode -

(Karlan & W, '07), (Kogut & R, '05)	(Small ea, '07), (Drouvelis & G, '16), (Caviola ea, '14)


### Barriers: Avoiding information, motivated reasoning in processing it

andreoni2017avoiding, Exley2016, Exley2015, dellavigna2012	Kellner_EA_2017


### Barriers: Perfectionism/deontological aversion to 'waste' (or excuse-driven, motivated reasoning), lack of tangibility (giving to a diffuse cause); Percieved lack of transparency, and perceived corruption overseas

"Overhead aversion, Information about recipients' deservingness -, ""Avoid uncertainties/excuses not to give/mental transactions costs
 - """

(Gneezy ea, '14), (Fong & O, '10), (Exley, '16b)	(Andreoni ea, '17), (Dellavigna ea, '12)

### Barriers: Social/geographic distance

(Info enhancing) social closeness of recipient -

?cuddy_ea_2007	(Sudhir ea, '16)

### 2b. Barriers: Strong local appeals ('the ask'), social obligations to give locally (and 'crowding out'/moral licencing)

(Meer, '11)


