# Breakdown of barriers {#barriers-breakdown}

<div class="marginnote">
Future work: relate this breakdown to others' decompositions, especially that of [@caviolaPsychologyEffectiveAltruism2021] and [@jaegerPsychologicalBarriersEffective2021]

</div>

## Conceptual breakdown of 'barriers' (first presentation) {#barriers-concept}

We focus on the 'barriers' or 'hurdles to giving effectively' among individuals who *already* engage in some charitable giving and other-regarding acts. Loosely, a donor would need to "jump over all of these hurdles" and cross each of these barriers in order to be giving effectively.

::: {.marginnote}
Consider: is there a well-known psychological framework for these sorts of multiple-hurdle choices?
:::

We first consider a fairly *conceptual* breakdown. (However, for the main organization, we will use a less theoretically-precise categorization that proved more practically usable.)

::: {.marginnote}
Later chapters present the direct and indirect evidence for very specific barriers, with real-world examples, and proposed 'tools' for surmounting these. In doing this, the conceptual breakdown proved difficult, as most of the real-world cases fell into multiple theoretical categories.
:::

\

```{block2,  type='note'}

**A conceptual breakdown of barriers:**

- Base values may be (non) utilitarian: People are optimising their own 'X', which does not coincide with impact $\rightarrow$ no puzzle?

- Avoiding information about effectiveness: Even if people want to optimise impact, they may specifically dislike and avoid gathering information about effectiveness in a charitable giving setting

- Presenting effectiveness information may backfire: E.g., if it switches off the 'generous part of the brain', gets people to think in a more 'market' mode, or makes people indecisive

- Judgement/cognition failures, quantitative biases, information failure: People try but fail to optimize, and/or have persistent incorrect beliefs

\

- Emotion overrides cognition: Our brain serves two masters, those decisions are not consistent


\

- Identity and signalling: Effectiveness in giving clashes with our self-image/self-beliefs, or with how we want to appear to others
\

- Systemic factors (and inertia): "It's society's fault, man" ... social systems leading to pressure and incentives from others to give to local or less-effective causes. Even if impact is a goal these systems take a long time to adjust.

```

```{=html}
<!--
(Yoruk, 2016), (Gneezy ea, '14)
yoruk_2016, Gneezy2014  brown_etal_2016, Chhaochharia_Ghosh_08?, Kinsbergen_tolsma_13
-->
```
### Are people utilitarian? {#are_we_util .unnumbered}

Most of our discussion above largely assumes that an individual is, at least to some extent:

i.  *Other-regarding/pro-social:* Her preferences or the "utility function she is maximizing" incorporates the well-being of others, at least to some extent

ii. *A moral utilitarian* (consequentialist): The value she places on helping others (or on others' outcomes) is principally increasing in some measure of the *amount* of good they have done for others, or in others' welfare. For a given personal sacrifice, she will always prefer to have made more people more well-off than to have made fewer people less well-off. In Economics terms, she strictly prefers and values *Pareto-improvements*.

::: {.marginnote}
To do: A mathematical statement of this may be helpful here.
:::

iii. *Agent-neutral* ('*universalist*'): In considering others' welfare, she values all others equally regardless of their identity. (Unfold for a precise example of this.)\*

     ::: {.marginnote}
     \* I believe this corresponds to a 'symmetric' welfare function in Economics.
     :::

```{block2,  type='fold'}

Agent-neutrality: a more precise example:

Consider a world with three other people (B,C,D). Suppose each begin in a poor state. Consider outcomes such as:

1. B and C are well off and D is poor

2. D is well-off and B and C are  poor

A universalist, as I define it, would always prefer outcome 1 over outcome 2. She would also rather achieve outcome 1 over outcome 2 with her charity, *no  matter the identity of persons B, C, and D.*

```

iv. *Not 'deontological':* She faces no other relevant absolute moral constraints (constraints such as 'do no harm in your actions, even if others are helped')

\

**To what extent does a 'moral utilitarian' (MU) consequentialist ethic govern beliefs and behaviour?** To the extent it *does*, limited effective giving represents a puzzling intention/action gap.

**However, for non-utilitarians this is no puzzle.** If other forces and motivations drive our giving choices, we might not expect these to be aligned with effectiveness.

It could be argued that the above is posed too starkly. People may embrace concepts such as utilitarianism, universalism, and cause neutrality, and at the same time be largely driven by other concerns and sympathetic to other moral frameworks. We may agree with statements that "all lives are equal" and "we should strive to do the most good for the largest number" but also support maxims such as "charity begins at home" and "giving is about supporting something you have a personal connection to."

::: {.marginnote}
While these statements may, strictly speaking, be contradictory, we shouldn't expect perfect consistency or constancy. Most people are not asked to rigidly join the deontological or utilitarian camp, and those who have not studied philosophy or social science may never have contemplated these issues directly.
:::

<!-- TODO: Citations here; I recall having seen evidence  and argumentation suggesting that people are far from consistently in one camp or another -->

Perhaps moral utilitarianism (MU) is relatively unimportant in most people's charitable choices. Even if this is the case, understanding the ways in which people *do* pursue their giving goals, and their obstacles and "biases" in doing so may suggest ways of making giving more impactful. For example, many donors may prioritize their local community, leading to their less-effective giving (from a universalist point of view). However, they might be persuaded to expand their definition of their own 'community', or more generally, expand their "moral circle" (discussed in [@crimston2018]).

<!-- Even if this is the case, specific campaigns, tools, and fundraising approaches may still help align their parochial, self-interested, or reputation-seeking values and intentions with more effective giving. -->

\

```{block2,  type='note'}

**Some examples of concerns other than Moral Utilitarianism that might drive giving and charity-choices:**

- Perfectionism/deontological aversion to 'waste'

- Social pressure

- Signaling virtue to others

- Emotional empathic reactions to particular images and situations

- A desire to identify with particular causes or particular groups of individuals, perhaps  in opposition to other groups

- Religious motivations

- Fairness concerns

```

\

### Judgement/cognition failures; Biases in perceiving impact and in making choices {#cog-failures .unnumbered}

People may (at least to some extent) *want* to be effective in their donation. However, they may simply not be good at doing this. Quantitative biases may drive departures from effectiveness in general. Anything that causes me to misunderstand effectiveness, to misapprehend the nature of the "production function for good outcomes", or to misjudge charities will lead me astray from effective giving. If I am making any mistake, I am failing to optimize. Furthermore, some biases may happen to be *particularly* harmful to those charities and causes that are most effective.

We consider these extensively in the section "[Barriers: Quantitative biases](#quant-biases)".

::: {.marginnote}
Cognitive biases include: - Overweighting and underweighting probabilities - Misunderstanding marginality - Scope-insensitivity - Opportunity-cost Neglect - Identifiable victims effect - Overhead aversion
:::

\

```{=html}
<!-- Responses: De-biasing, etc.

smallSympathyCallousnessImpact2007, gneezyAvoidingOverheadAversion2014, ein2013giving, kogut2005identified, kogut_2005b, Kinsbergen_tolsma_13 -->
```
<!-- (or excuse-driven, motivated reasoning), lack of tangibility (giving to a diffuse cause); Percieved lack of transparency, and perceived corruption overseas -->

```{=html}
<!-- Information about recipients' deservingness, Avoid uncertainties/excuses not to give/mental transactions costs
 (Fong & O, '10), (Exley, '16b) (Andreoni ea, '17), (Dellavigna ea, '12) -->
```
### Emotion overrides cognition {.unnumbered}

See section \@ref(analytical-grinch)

**Presenting analytical/impact information switches off system 1**

Charity effectiveness (info/deliberation)

-   Donor's mood (Impacting)

-   Affect prime

-   Evaluation mode

::: {.marginnote}
See: (Karlan & W, '07),[@kogut2005singularity; @kogutIdentifiedVictimEffect2005], [@Small2007], [@Drouvelis2016], [@Caviola2014]
:::

\

### Avoiding information, motivated reasoning in processing it

[See 'Cost-benefit analysis aversion'](#cba-aversion)

::: {.marginnote}
See: @andreoniAvoidingAskField2017, @exleyExcusingSelfishnessCharitable2016, @exleyImpactSurpriseDonation2018, @dellavigna2012testing, @reinstein2018commitments
:::

\

## Practical breakdown (organizing this resource) {#barriers-practical}

Most of this bookdown is devoted to classifying potential barriers to effective giving and assessing the general and specific evidence for these barriers. We use a more practical breakdown to organize this, particularly trying to avoid overlap between sections.

### [Barriers: Awareness, consideration, and distance distance (Physical, Psychological/Emotional, Social)](#aware-distance) {.unnumbered}

People may tend to give more to a cause/charity that they are more aware of, that they feel is more important and salient, and that they feel close to. Some causes will be *closer* to the mass of potential donors than others; this can include physical closeness, cultural proximity, and more. As a result, other causes may be relatively neglected. This relates to "moral circle expansion" but as well as quantitative biases such as the "availability heuristic".

::: {.marginnote}
Responses?: (Information enhancing) the social closeness of a recipient/beneficiary.
:::

Less proximate needs are less salient, thus under-funded.

### [Identity and signaling](#identity) {.unnumbered}

Considering effectiveness in giving (and publicizing this concern) may conflict with an individual's self-perception. It may also harm her reputation, at least relative to emotional or 'deontological' helping responses.

[@burumEvolutionaryExplanationIneffective2020]

Includes, e.g.,

-   social perceptions and 'signaling empathy vs effectiveness' ([@caviola2020many])

-   difficulty of coordinated signaling with a hard-to-coordinate measure such as 'effectiveness' @burumEvolutionaryExplanationIneffective2020

-   **Section** \@ref(identity)**: [Barriers: Identity and cognitive dissonance](#identity)**

<!-- Volunteer experience unlocks emotion and giving -->

-   **Section** \@ref(social)**: [Barriers: Signaling and social pressures/social identity](#social)**

-   social obligations to give locally (and 'crowding out'/moral licencing) (see, e.g., [@meerBrotherCanYou2011])

Does one contribution crowd out another? If so, social pressure, systems enforcing 'local public goods' and inertial factors may limit effective (non-local) giving.

```{=html}
<!-- #TODO: At some point we should make the point that in order for people to give effectively they need to know which charities are effective. For this to be the case, charities must transparently submit to rigorous metrics. Charities must advertise their impact and compete on this basis. For charities to want to do this, they must believe that donors as ‘consumers’ care about this.

According to Mulesky (2020) “Charities routinely appeal to impact when soliciting donations”; However, the example she gives is not a clear measure of per dollar impact.

However, a feature of philanthropy overlooked in published research is that nonprofit organizations rarely, if ever, support these claims with rigorous evidence
-->
```
-   **Section** \@ref(eval-aversion)**: [Barriers: Aversion/obstacles to doing (using) evaluations; effect of analytical information on generosity](#eval-aversion)**

-   **Section** \@ref(factual)**: [Barriers: Persistent and systematic incorrect empirical beliefs](#factual)**

-   **Section** \@ref(quant-biases)**: [Barriers: Quantitative biases](#quant-biases)**

-   **Section** \@ref(inertia)**: [Barriers: Inertia and systemic/institutional](#inertia)**\

# BARRIERS: DEFINITION & EVIDENCE {-}
