# (Do people actually care about impact? Does moral utilitarianism matter?) {#doesimpactmatter}  


## Are people utilitarian? {#are_we_util}

Fundamentally, our base values may be non-utilitarian. A universalist cause-neutral 'desire to help others' might *not* be what drives most giving.


Most of our discussion largely assumes that an individual is, at least to some extent:

i.  *Other-regarding/pro-social:* Her preferences or the "utility function she is maximizing" incorporates the well-being of others, at least to some extent

ii. *A moral utilitarian* (consequentialist): The value she places on helping others (or on others' outcomes) is principally increasing in some measure of the *amount* of good they have done for others, or in others' welfare. For a given personal sacrifice, she will always prefer to have made more people more well-off than to have made fewer people less well-off. In Economics terms, she strictly prefers and values *Pareto-improvements*.

::: {.marginnote}
To do: A mathematical statement of this may be helpful here.
:::

iii. *Agent-neutral* ('*universalist*'): In considering others' welfare, she values all others equally regardless of their identity. (Unfold for a precise example of this.)\*

     ::: {.marginnote}
     \* I believe this corresponds to a 'symmetric' welfare function in Economics.
     :::

```{block2,  type='fold'}

Agent-neutrality: a more precise example:

Consider a world with three other people (B,C,D). Suppose each begin in a poor state. Consider outcomes such as:

1. B and C are well off and D is poor

2. D is well-off and B and C are  poor

A universalist, as I define it, would always prefer outcome 1 over outcome 2. She would also rather achieve outcome 1 over outcome 2 with her charity, *no  matter the identity of persons B, C, and D.*

```

iv. *Not 'deontological':* She faces no other relevant absolute moral constraints (constraints such as 'do no harm in your actions, even if others are helped')

\

**To what extent does a 'moral utilitarian' (MU) consequentialist ethic govern beliefs and behaviour?** To the extent it *does*, limited effective giving represents a puzzling intention/action gap.

**However, for non-utilitarians this is no puzzle.** If other forces and motivations drive our giving choices, we might not expect these to be aligned with effectiveness.

It could be argued that the above is posed too starkly. People may embrace concepts such as utilitarianism, universalism, and cause neutrality, and at the same time be largely driven by other concerns and sympathetic to other moral frameworks. We may agree with statements that "all lives are equal" and "we should strive to do the most good for the largest number" but also support maxims such as "charity begins at home" and "giving is about supporting something you have a personal connection to."

::: {.marginnote}
While these statements may, strictly speaking, be contradictory, we shouldn't expect perfect consistency or constancy. Most people are not asked to rigidly join the deontological or utilitarian camp, and those who have not studied philosophy or social science may never have contemplated these issues directly.
:::

<!-- TODO: Citations here; I recall having seen evidence  and argumentation suggesting that people are far from consistently in one camp or another -->

Perhaps moral utilitarianism (MU) is relatively unimportant in most people's charitable choices. Even if this is the case, understanding the ways in which people *do* pursue their giving goals---and their obstacles and "biases" in doing so---may suggest ways of making giving more impactful. For example, many donors may prioritize their local community, leading to their less-effective giving (from a universalist point of view). However, they might be persuaded to expand their definition of their own 'community', or more generally, expand their "moral circle" (discussed in [@crimston2018]).

<!-- Even if this is the case, specific campaigns, tools, and fundraising approaches may still help align their parochial, self-interested, or reputation-seeking values and intentions with more effective giving. -->

\

```{block2,  type='note'}

**Examples of concerns (other than Moral Utilitarianism) that might drive giving/charity-choices:**

- Perfectionism/deontological aversion to 'waste'

- Social pressure

- Signaling virtue to others

- Emotional empathic reactions to particular images and situations

- A desire to identify with particular causes or particular groups of individuals, perhaps  in opposition to other groups

- Religious motivations

- Fairness concerns

```

\

## (Evidence) 

We consider the evidence that people 'are utilitarian' in this sense. However, it may be particularly difficult to get evidence about what people's core values and ethical beliefs *are*, whether they even *have* a consistent moral framework, and when and whether they are consistent in *acting* on this framework.


[@berman2018] suggest that charitable decisions are viewed as choices in which it is *not appropriate* to consider effectiveness.  See market versus social norms.





