# Barriers: Aversion/obstacles to *doing* (and using) evaluations {#eval-aversion}

## General cost-benefit analysis (CBA)-aversion or reluctance {#cba-aversion}

<div class="marginnote">
This is hard to label: 'aversion' may be the wrong word: people may finding it less appropriate/normal/virtuous to do CBA in a charitable context, or it may naturally not occur to them to do it.
</div>

<!-- integrate in 'CBA_Nick.Rmd' -->

### Description

People may be reluctant ^[how observed/manifested?] to consider the cost and benefits of the actions they are funding through their charitable donations (or they find this less appropriate/normal). This contrasts with a much greater willingness to consider these and other domains such as consumption, investment, and public policy. People also seem to avoid accessing/buying/seeing information (particular information that may be likely to feel compelled to give.)

### Theoretical/conceptual discussion

For this to be considered a bias, the relevant individuals must intrinsically value the usefulness of their charitable activity at least to some extent. I.e., they must be Moral Utilitarians, at least in part, or for some of the time. However, they may consider it very costly or distasteful to actually do this evaluation, or it may
clash with other motivations and tendencies.

This aversion also must be distinguished from a lack of *ability* to do CBA in the charity domain; the latter would instead be considered a  [quantitative bias](#quant-biases).

The reluctance to engage in this evaluation process may relate to the aforementioned ^[where?] "taboo trade-offs"; if these tradeoffs are taboo, considering them may involve great emotional distress.

[@Berman2018] refer to the idea that "believing that charity is a subjective decision licenses individuals to donate in personally gratifying ways." This perspective plausibly combines partial and conflicted Utililitarian preferences with the presence of moral licensing.

As Berman et al note, the belief that *CBA is not a natural part of the charitable domain* may stem from the lack of direct feedback one gets from donating (in Economics terms, a "credence" good) relative to consumption and investment goods. <div class="marginnote">
(they cite: Imas paper?)
</div>

Several papers^[ref] find that people are reluctant to pay for---or actively seek to avoid--- certain information. However, these may reflect motives distinct from CBA, such as a self-serving bias.  

<div class="marginnote">
On the other hand ...  a majority ranked effectiveness [how highly?] as a crucial criterion to select a charity and reported greater happiness when the impact of their contribution wasis highlighted.(van Iwaarden et al. 2009; Aknin et al., 2013) 
</div>

### Relevance to Effective Giving

If *determining which charity is effective* requires CBA people may avoid doing so. If effective charities *force* people to consider CBA then people may avoid these charities in order to avoid having to do these evaluations.

### Evidence

#### Evidence for  "People sometimes actively avoid information about charity effectiveness that would motivate doing a CBA..."

[@Fong2010] run dictator game experiments involving payments to real-life welfare recipients living in 178 public housing in Pittsburgh;  each subject is matched with a particular recipient  of their potential donation. In their *"Choice treatment",* a subject can choose to pay \$1 to learn about a recipient's drug use or disability, information meant to suggest the deservingness of the recipient. "We find that a third of the dictators are willing to pay money to learn more about their recipient. Dictators who acquire information mostly use it to withhold resources from less-preferred types, leading to a drastic decline in aggregate transfers." 

But this needs to be interpreted carefully:  *those who decide not to buy information appear less generous than the average*!


<div class="marginnote">
[@Dellavigna2010] provide evidence that people will pay costs to avoid being asked and avoid social pressure. However, for this same case *if* they are asked they then to respond by giving. While "avoiding the ask" is not avoiding cost-benefit analysis, it suggests that people are in fact strategic in avoiding things that  may make them feel compelled to donate. 
Note: This evidence is only tangentially relevant.
</div>


#### Evidence for "People rarely seek out effectiveness information and are reluctant to purchase it"


<!-- TODO - Cite: That survey-based study where few people say that they have
looked into the effectiveness information on the charities they donate
to -->

In [@Null2011], in a final stage of her experiment:

> Subjects were given the option to spend USD 5 of their total gift to the
> development charities in order to find out which of the three would
> receive a matching rate of USD 3 (the other two would receive matching
> rates of USD 1.50). Altruistic subjects whose donation was at least USD 20
> and gave to all three charities, or whose total gift is greater than
> USD 35 and gave to two charities, would find it profitable to purchase
> the information. ... (84%) met these criteria on gift size and number
> of charities supported.

> ...only 40% of subjects were willing to give up a small portion of
> their endowments in order to find out which charity would receive the
> highest rate; the rest preferred to allocate their gifts without
> knowing what they would be worth to the charities."

> \...These subjects \[who chose not to purchase the information\]
> forfeited matching funds ranging from 30-150% of the value of their
> unmatched gifts, with the median donor sacrificing matching funds
> exactly equal to the value of her unmatched gift, a truly staggering
> sum.

Null attributes this failure to buy information either to subjects who "simply did not care about the potential to substitute into the charity with the highest matching rate", perhaps driven by some form of simplistic warm glow motive, or to simple misunderstanding or fatigue (in an incentivized elicitation, she found some evidence of incomplete comprehension). To the extent this is *not* a misunderstanding, it might be seen as evidence of CBA aversion; participants did not want to purchase evidence that would require them to do calculations in this domain.

\

#### Evidence for "People do not respond 'efficiently' to information about costs and benefits"

Null (2011) ran a set of experiments at Kiwanis/Rotary clubs and with "professional subjects" (university administrators?) at the Berkeley X-lab; the former strictly involved allocations *among* charities, in the latter case what was not given away could be kept. For the main reported treatments, participants made a series of decisions under different incentives (mostly on the same page and thus simultaneously?). The "prize" was \$100; in each session only one decision from one subject was chosen for actual payment/donations.

Many participants who choose to donate positive amounts to multiple charities in earlier (?stages) continue to donate to multiple charities when one charity is given a better match rate; they only "imperfectly substitute" (and some even substitute away from the now "lower-priced" charity). She attributes this to both risk aversion (diminishing utility in to each charity's actual impact, along with uncertainty about this impact) as well to as a version of "warm glow" with a diminishing marginal benefit in the amount given to each charity.[^1] However, this could also be attributed to a simple failure to make these cost-benefit calculations (as she also found some evidence suggesting misunderstanding
of the nature of these incentives).

<!--
> ***\[Cut?*** [^2]***Metzger and Gunther (2015)*** ran an (Economics)
> lab experiment where (some) participants had the opportunity to buy
> information about a real (but unnamed) NGO and then to make a real
> donation to it (from their lab earnings). They vary whether the
> information pertains to the effectiveness of the program (number of
> years of education it provides per Swiss franc), the organizations'
> administrative cost rate, and the recipient type (children in
> impoverished countries versus young Swiss artists). They find that a
> reasonable minority of people choose to purchase this information; 41%
> in the " recipient type" treatment, 28.3% in the "administrative
> costs" treatment, and 18.5% in the "aid impact treatment" (only the
> largest difference is significant). **\]**

*Additional interpretation of the above: some people fundamentally seem
to not care about the money once it has left their hands, at least when
it is framed in terms of [money]{.underline}*
-->

#### Evidence for "people accept and value subjectivity in the charitable domain more so than for other choice domains"

***Berman et al (2018)*** provide evidence from a series of five survey/vignette experiments; unlike those mentioned above, these (mostly) involve hypothetical choices among *multiple* causes. All experiments use standard subject pools (behavioral lab subjects or m-turkers) with reasonably large samples. All ask for hypothetical (Likert-scale) responses involving fictional charities, investments, and other scenariae; they mostly rely on between-subject responses, and their statistical analyses report reasonable tests on the relevant comparisons. 

Their "Study 1: Perceived Subjectivity of Charity" found that, in rating statements such as "it is important that the ______ I choose reflects my personal tastes or values" and "It is more important to rely on objective measures rather than personal feelings when choosing ______  \... they found people agreed more with the *subjective/taste* approach when assigned a treatment where the blank was "Charity", relative to those assigned treatments involving medical treatments, investments, and cel phones. (But less than some other things like art, and similar to restaurants in some tests!) 

Their "Study 2: Personal Feelings Versus Welfare Gains" presented participants with "Mary" and a pairing of fictional domestic (homelessness) and international (micronutrient) charities, presenting effectiveness information on both (clearly favoring the latter). The treatment\-- which charity Mary felt an emotional connection to\-- had a significant impact on the response to "Which charity should Mary donate to", in the predicted direction. They were also asked: "Which option does the greatest good for the greatest number of people?"; here responses favored the international charity for both treatments; but even so, when Mary felt connected to local charity, participants favored donating there.

<div class="marginnote">
Berman et al argue that their results demonstrate the acceptance of the suggestive preferences is somewhat attenuated by the \"role of responsibility\", but it\'s not clear what this term means or how this could be relevant to voluntary individual giving. </div>
 
 In their "Study 3: Charity Versus Investment Choice", subjects were assigned categories and fictional examples of either charities or investment, and presented domain categories and effectiveness information for each. Fewer participants in the charity treatment (relative to the investment treatment) chose to sort by effectiveness rating, and fewer chose the highest rated option.

 In Study 4, they find that, in rating research departments for funding, participants pay more attention to charity effectiveness ratings when the are given the "role" of a "president of a local medical research center" rather than a donor. Similarly, in Study 5 participants assess someone who allocates funds to a research department; participants respond to the effectiveness of the department chosen more when rating the decision quality and altruism/selfishness of a "president..." than rating a "donor". 
 
Overall, these suggest that, when considering charitable donations,
people tend to favor--or at least to accept--the use of subjective
preferences and personal ties, rather than objective information, and
they do so more than for more "standard" goods and choices. This is more
accepted for "donors" than for people with responsibility for others'
funds. <div class="marginnote">
Berman et al argue that their results demonstrate the acceptance
    of the suggestive preferences is somewhat attenuated by the \"role
    of responsibility\", but it\'s not clear what this term means or how
    this could be relevant to voluntary individual giving.

</div>
 However (as they do note), the effectiveness information
still has *some* (positive) effect on participants' responses; it is not
ignored. Their experiments also do not analyze the *avoidance* of
information or CBA.

**Methodological strengths and weaknesses:** ...(E.g., hypothetical
nature of choices; some evidence these are not taken seriously; specific
context in vignettes allow alternative interpretations...)

[^1]: She also introduces exogenous risks over matching rates, and notes
    that roughly 2/3 of those that choose to shift only imperfectly are
    not measured to be \"risk averse\".

<!-- [^2]: DR: This could have been a very worthwhile study, but I think it
    has a number of obvious flaws with its design and the potential to
    interpret it in terms of willingness to pay for real effectiveness
    information for doing a CBA. (For example, the artist versus poor
    children recipients would also seem to be an effectiveness measure)
    so I'm not sure it's worth reporting on.\]
-->

## Market versus social norms

"People see charity as in the social 'domain' not the market one, and thus find it strange to apply CBA to it. 
"

## Cost effectiveness information may turn off System-1 and reduce giving; statistics diminish impact of 'identifiable victim'

References: small2007sympathy_s3_s4, small2007sympathy_s1_s2, karlan2017effect, "Parsons, 2007", bergh_Reinstein	smeets2015giving

See also: karlan2017effect, "Parsons, 2007"

<!--DR: A related memo-- https://www.dropbox.com/s/t4lq8x9lqeg6gt9/practicalpresentingimpactinfo.pdf?dl=0-->
