# Barriers: Inertia and systemic/institutional {#inertia}


## Social norms

Social norms promote giving to traditional non-EA causes and fundraisers, and responding to peer requests. --> crowding out? Norms may also suggest giving to causes like AMF is "weird".

\

**Asks** (Own category?)

Donation requests increase the propensity to give [@yorukHowResponsiveAre2009]. There is a conventional wisdom that "most donations occur in response to an ask".  If there are systematic asks for non-EA causes this may crowd out EG.

### Subjectivity in the charitable domain - Evidence from @Berman2018

One social norm that could pose a barrier to effective giving is people viewing charity as a relatively subjective decision, where people feel that they are justified in donating based on their own personal preferences rather than on the basis of efficiency. This is a concept that has been examined by @Berman2018, who argue that “believing that charity is a subjective decision licenses individuals to donate in personally gratifying ways at the cost of maximizing welfare”. Consequently, the social norm of viewing charitable decisions as highly personal and subjective could prove a significant barrier in encouraging effective giving. 

<div class="marginnote">
@Berman2018 also point to @goodwin2008psychology for an examination of ‘objectivism’ generally, and @spiller2017consumer for their discussion of objectivity in consumer decisions.
</div>

@Berman2018 conducted five studies to look at the role of subjective preferences in charitable giving, which are discussed [below](#studyone), but are summarized by @Berman2018 as follows:

> Study 1 showed that, relative to personal decisions, individuals view charity as being relatively subjective. Study 2 showed that individuals prioritize emotional connection over welfare maximization when comparing charity options. Study 3 examined choice processes and found that people are more likely to override welfare maximization when choosing a charity than when choosing a financial investment. The final two studies found that individuals are less likely to license themselves (Study 4) and others (Study 5) to select an ineffective option when a decision maker assumes a position of responsibility.

<div class="marginnote">
These studies are also discussed and evaluated [here](#subjectivity)
</div>

#### Study 1 {#studyone}

The first study from @Berman2018 used the following method: 

> Participants were asked to evaluate how they believe they should make decisions across six decision domains (choosing a charity, an investment, a cell phone, a restaurant, a piece of art, and a medical treatment). Specifically, they evaluated the extent to which they agreed with the following statements: “It is important that the _____ I choose reflects my personal tastes or values,” “It is more important to rely on objective measures rather than personal feelings when choosing _____,” and “Objective measures are the best way to choose _____.” Responses were made on a scale from 1 (*not at all*) to 7 (*very much so*). 

The study found that participants thought that using subjective preferences over objective metrics was more important when choosing a charity, compared to choosing a cell phone, an investment, or a medical treatment. They also found that “The importance of relying on subjective preferences for a charity preference was roughly on par with choosing a restaurant… Only choosing a piece of art was evaluated to be more of a matter of subjective preference than choosing a charity”. 

This led @Berman2018 to conclude that this study demonstrated that people view giving to charity as a highly personal and subjective decision, and "not necessarily one that should be made using objective measures”. 

#### Study 2

The second study from @Berman2018 looked at “whether people believe it is normatively appropriate to discount welfare-maximizing options in order to choose a more subjectively preferred charity”. In other words, is it viewed as acceptable for an individual to choose the charity that they care more about over the charity that does the most good? They used the following method: 

> Participants read a scenario involving Mary, who was looking to donate money to one of two hypothetical charities. One charity, Hunger Care in Africa, was described as providing micronutrients for children in Africa, and for each USD 100 donated, this charity could feed five children for a month. A second charity, Jump Start Your Community, was described as training and educating the homeless in Mary’s community, and for every USD 100 donated, this charity could provide 2 hr of job training to one homeless person
> Each participant was then randomly assigned to one of two emotional-connection conditions. In the local-causes condition, participants read that Mary feels an emotional connection toward helping people in local communities, whereas in the distant-causes condition, participants read that Mary feels an emotional connection toward helping those in third-world countries 
> We then presented participants with two different questions on separate pages in random order. One question assessed where they felt Mary should donate (“Which charity should Mary donate to?”), whereas the other question asked which charity was the most effective at maximizing social welfare (“Suppose that Mary wanted to donate to the charity that did the greatest good for the greatest number of people. Which one should she donate to?”). Both questions were measured on a 7-point scale from 1 (definitely Jump Start Your Community) to 7 (definitely Hunger Care in Africa)

They summarized their results from this study as follows: 

> When participants read that Mary felt an emotional connection with distant charities, they responded that she should donate to Hunger Care in Africa… and also evaluated it as being more effective… However, when Mary felt connected to local communities, they indicated that she should donate to Jump Start Your Community…, despite indicating that Hunger Care in Africa was more effective

#### Study 3 

Study 3 built on the ideas from Study 1. Effective altruism suggests that to make the biggest difference, people should try and maximize welfare, similar to how investors try and maximize their financial returns. However, Study 1 suggested that individuals viewed objective information as more important in making financial decisions than in charitable decisions. The third study from @Berman2018 tries to more directly compare the two, using the following method: 

> Participants were also told that the website organizes options into six different categories (alternative energy, cancer, education, food, housing, and international). These categories were chosen because they could plausibly represent groupings of either charities or investments.
> Participants were then given the choice to sort the options either by effectiveness or by category type. Sorting by effectiveness suggested that an individual was primarily concerned with selecting one of the most effective charities or investments, whereas sorting by category suggested that an individual was primarily concerned with selecting a charity or investment that reflected a preferred option type

<div class="marginnote">
There is significantly more detail on the methodology of this study in the full paper from @Berman2018, and there is a discussion of additional measures, a mediation analysis, and robustness check studies
</div>

They found that participants were significantly more likely to sort by effectiveness in the investment condition than in the charity condition. Furthermore, when the options were ranked, “participants chose a less effective charity… than investment”.

#### Study 4 

Study 4 and 5 both examined how responsibility changes people’s perception of how important objective information is. Berman et al. hypothesized that “when individuals assume a role of responsibility, they may feel obligated to act in accordance with the welfare of the entire group and will discount their personal preferences to do so”. 

In Study 4, participants were assigned to a donor condition or a president condition, and then participants were either given information on effectiveness ratings, or there was no mention of effectiveness ratings.

> Participants assigned to the donor condition imagined that they lived near a local research center. Participants assigned to the president condition imagined that they were the president of a local medical research center. Participants in the donor condition were then told that “because the market has done well, you have more cash than usual. You would like to help by making a donation to medical research.” Participants in the president condition were told that “Because the stock market has done well, the research center has more cash than usual. As president, it is part of your job to allocate these funds to conduct additional medical research.”
> Each participant was then given his or her choice between allocating funds to one of three departments, with effectiveness ratings provided for each department… These ratings were purposefully selected so that the most intuitively appealing choice was rated as the least effective (cancer), and the least appealing choice was rated as the most effective (arthritis), thereby creating a tension between the option that would be most personally gratifying and the option that would maximize welfare

Their results suggested that people paid more attention to the effectiveness ratings when they were in a position of responsibility:

> When the effectiveness ratings were absent, the assigned role did not significantly affect the option that participants chose… However, when the ratings were present, participants in the president condition were significantly more likely to select higher rated options than those in the donor condition… Although participants used effectiveness ratings when given this information, significantly more did so when placed in a position of responsibility

#### Study 5

Their fifth study used a similar methodology to examine “how individuals judge others who select either a relatively effective or an ineffective option”, using the following methodology: 

> The study has a 2 (role: donor vs. medical center president) x 2 (choice: most effective option vs. least effective option) between-subjects design. Participants read a scenario about Mr. Peterson, an individual who was allocating money to a local medical research center. In the donor condition, participants read that Mr. Peterson was looking to donate money from recent stock market gains to a department within the medical center. In the president condition, participants read that Mr. Peterson was the president of the medical research center and that he was looking to allocate surplus funds from recent stock market gains to a department within the medical center
> In all conditions, participants then read about an independent research firm that evaluates the effectiveness of departments in the same fashion as the previous study 
> ... Participants then evaluated the extent to which they thought the decision was responsible, appropriate, and thoughtful

As with Study 4, the results suggested that people thought effectiveness information was more important for people in positions of responsibility: 

> In both the president and the donor conditions, participants felt that Mr. Peterson’s decision was of lower quality when he selected the least effective option over the most effective option. However, the drop in decision quality was significantly greater when he was president… than when he was a donor
> In both the president and the donor conditions, participants felt that Mr. Peterson’s decision was less altruistic when he selected the least effective option over the most effective option. However, this difference was greater when Mr. Peterson was president… than when he was a donor

#### Conclusions

Analysing the results of their five studies, @Berman2018 conclude that: 

> Our results suggest that people view charity decisions as being relatively subjective, which inhibits the impact of effectiveness information on welfare maximization. Thus, to persuade people to make donation decisions that maximize social welfare, providing information alone may not be sufficient. Rather, it may require altering how individuals view their role as a donor altogether


## Consider: inertia and obstacles to charities collecting, evaluating, and sharing impact information 

<!-- 

Mulesky: 
  
Even international health and humanitarian charities recognized as being unusually transparent keep details about their cost-effectiveness confidential. For example, in 2012 a representative from Médicines San Frontières told GiveWell that it regularly conducts program evaluations, but only a small number were publicly available. According to MSF, “sharing more program reports would take excessive time and resources” (GiveWell, 2012). Informal discussions with evaluation staff reveal that charities sometimes intentionally conceal the information from the public when the evaluations demonstrate the ineffectiveness of the organization’s program. For example, according to an interview with an evaluation consultant, Handicap International (HI) hired external evaluators to assess the impact of its antenatal care program for women in the Democratic Republic of the Congo three years into the project. The results “showed that the program hadn’t met any of its targets – it was a failed program with all the investment wasted.” After presenting the evaluation’s findings to staff in Brussels, the report was never disseminated beyond those in attendance, and “for all anyone knew it was a ‘success’...The message didn’t penetrate within the organization
--> 
