-   Only put notes in this file if they otherwise will bog down the
    > [[main
    > draft]{.underline}](https://docs.google.com/document/d/1KcqGEvU_kPt-uT0NHxcE7BDubmwWihfLsrzYUK7a3PY/edit#heading=h.cgxeifmj9okb);
    > e.g., meandering discussion, long quotes from other authors we
    > need to refine

## Presenting the puzzle and challenge: Our ineffective giving

**Utilitarianism**

**(Motivation) Why should you care about this?** Descriptives of giving
(US, international) and how \'ineffective\' it is. Potential global
welfare gains to changing "where we give."

**Research Question/Problem: Why don't people give in an evidence-based
way?**

[What are the psychological motivations for not giving
effectively?.]{.underline}

### Previous literature reviews and surveys, lack of previous work

[Effectiveness-specific]{.underline}:

**Comparison of outlines**

-   Gertler, "[[Charitable Fundraising and Smart
    > Giving]{.underline}](https://aarongertler.net/wp-content/uploads/2018/01/Aaron-Gertler-Senior-Thesis-full-bibliography-1.pdf)\"

-   Baron chapter

    -   Introduction (with problem/puzzle)

> \- Possible Nonutilitarian Heuristics
>
> Evaluability (focus on attributes easy to evaluate e.g.,
> efficiency/overhead) \["\"instead, what is more evaluable than the
> lives saved per dollar of contribution is the operating cost per
> dollar\"\]

-   Average vs. Marginal Benefit, Diversification, Prominence,
    > Parochialism

-   Identifiability, Voluntary Versus Tax

```{=html}
<!-- -->
```
-   Experiments

-   Waste, Average Cost

-   Diversification,

-   Unequal Efficiency; Unequal Efficiency, Several Projects Versus One

-   Nationalism

-   Forced Charity

```{=html}
<!-- -->
```
-   Discussion: Utilitarian Models of Altruism, Maximize Total Utility,
    > Limited Self-Sacrifice, Limited Altruism, Moral Education,
    > Implications

### 1.  1a. Who does give effectively? (or put at bottom?)

###     1b. Why (under what models) is this a puzzle?

### -   1.  1c: Are charities in competition? Is the ineffective giving reducing effective giving? Ask people to give to EA charity \'instead\'?

2.  2. Explaining the puzzle: Barriers to EA giving and potential responses, evidence
    =================================================================================

    Inclusion criterion: If we could snap our fingers and remove this
    barrier from the world, would this disproportionately increase
    Effective Charities?

    [Initial "Todo" for each:]{.underline}

    1\. Definition and discussion of the barrier and how it is relevant
    (and theoretical connections) \[and why an EA-specific barrier, and
    why it is distinct from the other barriers mentioned\]

    2\. Characterization and assesment of evidence for this barrier in
    general

    3\. Characterization and assesment of evidence for this barrier for
    (effective) charitable giving

**To Include:**

-   Distance

    -   Spatial/Physical: parochial altruism/ingroup bias

    -   Temporal (future problems and people)

    -   Social/Cultural \-- homophiily; (interpersonal and identity
        > e.g., race, gender, age, etc); also Solicitor characteristics

    -   Hypothetical (probability to happen)

    -   Emotional ([[Small's
        > paper]{.underline}](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.183.827&rep=rep1&type=pdf))

-   Market & Social Norms

-   Taboo Trade-Offs (c.f., Protected Values)

    -   People feel uncomfortable thinking about the effectiveness,
        > e.g., in terms of lives

-   Scope insensitivity (\#MisunderstandingStatistics)

    -   definition:

-   **Proportional dominance effect**

    -   Other terms: drop in bucket, psychosocial numbing,
        > psychophysical numbing,

    -   definition:

-   Availability heuristic/underweighting probabilities

-   Number of deaths (they're already dead)

-   Consistent problems aren't in the news

-   Marginal vs. average donation (consider, e.g., publicized and funded
    > disaster vs. other disaster; tsunami vs Pakistan)

-   **Small's cost effectiveness information ([[psych science
    > '18]{.underline}](http://journals.sagepub.com/doi/abs/10.1177/0956797617747648))**
    > tied to **Cost-Benefit Aversion/Disinterest** (see theorized)

-   **Effectiveness info shuts down giving** (Karlan/Bergh?)

-   Statistical victim effect/Identifiable victim

**Maybe**

-   Social norms

-   status quo bias / systems justification

-   Asks

-   Overhead aversion[^1] AKA evaluability bias (Caviola paper + Baron
    > chapter)

-   Risk aversion (c.f., hypothetical distance) + Loss aversion

-   Biased information search

-   Reference point

-   Volunteer experience increases empathy

**Theorized:**

-   Cognitive dissonance and identity

-   Opportunity cost neglect

-   Self-interest/local public good

-   Cost benefit aversion

**No:**

-   Defaults

-   lack of tangibility

9.  1.  ### Functional barriers: Obstacles to \*doing\* evaluations

        (Again, things that make people reluctant to evaluate and
        consider the effectiveness of charities, and ways that doing
        these evaluations reduce generosity)

### Market & Social Norms11

### Taboo Trade-Offs (c.f., Protected Values)

### Cost effectiveness information may turn off System-1 and reduce giving; statistics diminish impact of \'identifiable victim\'

### Cost-benefit analysis (CBA) aversion (or simply finding it less appropriate/normal/virtuous)

**Description**

***Theoretical/conceptual discussion***

**Relevance to EG**

**Evidence**

*Discussion/evaluation of general evidence*

*Discussion/evaluation of specific evidence here*

***Berman et al, '18 \-- fuller notes and discussion***

Abstract:

\> We found that even when effectiveness information is made easily
comparable across options, it has a limited impact on choice.
Specifically, people frequently choose less effective charity options
when those options represent more subjectively preferred causes. In
contrast to making a personal donation decision, outcome metrics are
used to a much greater extent when choosing financial investments and
when allocating aid resources as an agent of an organization

Note: these are all \*hypothetical\* choices.

This paper extends previous research on how people \"appear to be
-distorted altruists--- they care about welfare maximization, but
without clear information to make comparisons, they rely on their
feelings to guide choice (Loewenstein & Small, 2007; Slovic, 2007)\".
The novelty here is the use of \"effectiveness information is provided
across multiple different causes\" rather than a single cause.

Their main theoretical characterization of their results:

\> \...individuals view charity as a relatively subjective decision \...
believing that charity is a subjective decision licenses individuals to
donate in personally gratifying ways at the cost of maximizing welfare

Summary of results

\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--

Note, all studies use behavioral lab/students or Mturkers; all decisions
are hypothetical.

Study 1: Perceived Subjectivity of Charity \-- In rating statements (1-7
likert) like \"It is important that the I choose reflects my personal
tastes or values\" vs "It is more important to rely on objective
measures rather than personal feelings when choosing\" \... they agreed
more with the \*subjective/taste\* approach for charity relative to
choosing investments, cel phones, or (marginally) restaurants, but less
so than for a piece of art.

Study 2: Personal Feelings Versus Welfare Gains \-- \" When participants
read that Mary felt an emotional connection with distant charities, they
responded that she should donate to Hunger Care in Africa (M = 5.26, SD
= 2.05) and also evaluated it as being more effective (M = 5.59, SD =
1.87), t(197) = -1.19, p = .24, d = −0.17, 95% CI = \[−0.44, 0.11\].
However, when Mary felt connected to local communities, they indicated
that she should donate to Jump Start Your Community (M = 3.00, SD =
1.99), despite indicating that Hunger Care in Africa was more effective
(M = 4.55, SD = 2.32), t(202) = -5.12, p \< .001, d = −0.72, 95% CI =
\[-1.00, −0.43\].\"

\- but note that Mary\'s connection to the charity also affects the
stated \"effectiveness\" response!

Study 3: Charity Versus Investment Choice: Subjects assigned categories
and fictional examples of either charities or investment, and told their
domain category and effectiveness. Asked to sort these \[how
justified?\], \"significantly fewer participants chose to sort by
effectiveness rating in the charity condition (67.8%) than in the
investment condition (83.4%), -2 (1, N = 401) = 13.20, p \< .001, - =
.1\" \"Significantly fewer participants chose the highest rated option
in the charity condition (32.2%) than in the investment condition
(50.3%), -2 (1, N = 401) = 13.52, p \< .001, - = .1\"

Study 4: Decision-Making Role and Welfare Maximization

2x2 \-- Participants given a \"donor condition\" or a \"president of a
local medical research center\" condition and were \[not\] given
effectiveness ratings for each \"department (arthritis = 92, heart
disease = 86, cancer = 74). \... selected so that the most intuitively
appealing choice was rated as the least effective (cancer)\"

\"Results revealed a significant Role - Effectiveness Ratings
interaction\"; the effectiveness information had a positive impact for
both, but a larger one in the \"president\" scenario \[But is this
specific scenario comparison s relevant to charities; hospital president
has a distinct role, and this was a choice essentially within the
\*same\* charity\]

Study 5: Judgments of Decision Quality

Similar setup as study 4, but subjects assess the (\"percieved\")
\"decision quality\" and \"altruism\". Analogous results to study 4 for
both. \[The altruism result is puzzling: what justifies this? Are they
answering these questions carefully?\]

10. ### Functional barriers: Quantitative biases

    (Problems dealing with numbers and making logical evaluations
    involving numbers, values and amounts. Common cognitive errors
    \*or\* intuitive and emotional reactions triggered in these
    contexts.)

### Scope insensitivity

### Proportional dominance effect/drop in bucket/psychosocial numbing

**Fetherstonhaugh et al 1997** (notes)

S1: "Undergraduate volunteers (n = 54) from two sections of an economics
statistics course"

\> Studies 1 and 2 found that an intervention saving a fixed number of
lives was judged significantly more beneficial when fewer lives were at
risk o anverall. Study 3 found that respondents wanted the minimum
number of lives a medical treatment would have to save to merit a fixed
amount of funding to be much greater for a disease with a larger number
of potential victims than for a disease with a smaller number.

\> Study 1: Respondents evaluated the programs in pairs, one pair per
page

"imagine themselves as a government official of a small, developing
country"

\> We predicted that preference ratings would be greater for the
small-camp program than the large-camp program. Because these programs
were never paired together, however, we compared respondents' ratings
for the two Rwandan programs in pairings that shared a common
non-Rwandan program

\> Even though most respondents realized that the same number of
refugees could be saved in either camp, they preferred the small-camp
program (M 5 .45) over the large-camp program (M 5 2.20) when paired
with either the transportation or employment programs.

\> Study 2 omitted dummy scenarios and had respondents evaluate Rwandan
scenarios individually.

\> \... manipulated three within-subjects variables: size of refugee
camp (11,000 or 250,000), amount of pure-water aid a camp was receiving
before a water-purification plane was sent (low or high), and
reliability of the plane (60% or 100%). \... eight different scenarios
participants read\... 2 x 2 x 2 repeated-measures factorial design. All
respondents evaluated the same eight scenarios

\> two dependent variables: (1) the rated benefit of sending a plane,
and (2) a yes/no decision on whether or not to send a plane.

\> A 2 x 2 x 2 within-subjects ANOVA on respondents' benefit ratings
provided strong support for the psychophysical numbing hypothesis (see
Figure 2). A significant main effect for camp size, F (1, 132) 160.5, p
.001, indicated that respondents believed sending the planes to small
camps was more beneficial (M 6.46) than sending them to large camps (M
4.54). A main effect for the prior-aid variable, F (1, 132) 15.35, p
.001, indicated that respondents believed sending the planes to camps
that were already satisfying a substantial portion of their clean-water
need was more beneficial (M 5.73) than sending them to camps that were
only satisfying a small portion of their water need (M 5.27).

Gertler's discussion:

\> Participants were less likely to allocate money to a hypothetical
refugee camp when they could only save 1500 lives out of 250,000
refugees rather than 1500 lives out of 11,000. \... Fetherstonhaugh et
al. use the term "drop in the bucket" to describe the thought process
that might bring about these decisions: saving a tiny percentage of a
population could feel useless even if 1500 individuals still get the
chance to live.

**Jenni and Loewenstein (1997)**

It is widely believed that people are willing to expend greater
resources to save the lives of identiﬁed victims than to save equal
numbers of unidentiﬁed or statistical victims. There are many possible
causes of this disparity which have not been enumerated previously or
tested empirically. We discuss four possible causes of the "identiﬁable
victim effect" and present the results of two studies which indicate
that the most important cause of the disparity in treatment of
identiﬁable and statistical lives is that, for identiﬁable victims, a
high proportion of those at risk can be saved.

12. ### Functional barriers: Awareness and consideration

    (Whether a cause/charity is something people are aware of, feel is
    important/salient, and feel close to.)

    ### Functional barriers: Identity

    (Things that run against one\'s self-perception and how one believes
    others will will see you.)

    ### Functional barriers: Inertia and systemic/institutional

    (Factors limiting individual and social \*change\* in behavior)

    ### Functional barriers: Inherent

    (Longstanding or inherent societal and material factors)

## Tools for motivating EA giving

(See esp "EA-concepts" airtable)

**Accepted**

-   Tragic trade offs

**Maybe:**

-   Evidence of Impact?

-   Bergh's findings?

-   Charity quality ratings? (Charity navigator?)

-   Slowing people down: David's study

-   Ranking charities: David's study (Precommitment, foot in door,
    > cognitive dissonance)

-   Targeting

-   in name donations

-   Unit-asking

-   Andreoni: avoid impulse giving with avoiding asks

**Theorized:**

-   Cognitive Dissonance Reduction (opportunity to do *better)*

-   Opportunity cost salience

-   Reframing as loss to get risk seeing tendency

-   Overhead covered -\> Reduce crowding out?

-   Joint evaluation:

-   Luxury tax donations

-   Legitimation of small donations

-   present small base group

Harmful:

-   debiasing statistical victim

-   effectiveness information

General-powers

-   Identifiable victim

-   Depict suffering/depict happiness: direction unknown

-   Enhancing social closeness (homofily too?)

-   Unconditional gifts

-   Give more tomorrow/ Give if you win

-   Donor mood

-   Publicize donations automatically

-   Give social norm history (lots of past donations)

-   Recognition tiers

-   Earmarking money

-   Urgency

-   Kama Muta

-   seed money

Rejected:

-   Presenting blame/deservedness

### 1.  3a. Psych/behavioral tools; applicability to EA charities

###     3b: De-biasing and misperception-correction

(Kogut & R, \'05) (Caviola ea, \'14)

### 3c. innovative proposals

Smeets?, Kellner\_EA\_2017

### 3d. EA-movement approaches and pitfalls

## 4. Conclusion; summary of a research agenda

**Works Cited**

***SCIENCE OF GIVING: Experimental Approaches to the Study of
Charity***. PSYCHOLOGY Press, 2015.

[^1]: \[Which?\] Study finds 'no correlation'\-- is it convincing? Does
    working abroad increase overhead? Most relevant tie: doing impact
    evaluation will itself increase overhead
