#  Inertia, systemic obstacles {-#inertia}

## Social norms

Some of the social norms around charitable giving could work against the ideas of effective altruism. @cialdini1998social define social norms as follows:

> Social norms are rules and standards that are understood by members of a group, and that guide and/or constrain social behavior without the force of laws. These norms may emerge out of interaction with others; they may or may not be stated explicitly, and any sanctions for deviating from them come from social networks, not from the legal system

@elster1989social explains how the use of social norms could pose a problem for how rational individuals are, and how as a result social norms could contribute to inefficiencies:

> One of the most persistent cleavages in the social sciences is the opposition between two lines of thought conveniently associated with Adam Smith and Emile Durkheim, between *homo economicus* and *homo sociologicus*. Of these, the former is supposed to be guided by instrumental rationality, while the behavior of the latter is dictated by social norms... The former adapts to changing circumstances, always on the lookout for improvements. The latter is insensitive to circumstances, sticking to the prescribed behavior even if new and apparently better options become available

If social norms can cause departures from efficiency, then this could be considered as one of the causes of 'ineffective' altruism. It should be noted that this comparison between *homo economicus* and *homo sociologicus* is similar to a distinction offered by @Thaler2008. They similarly argued that we should understand human behaviour by viewing people as 'homo sapiens' rather than 'homo economicus', as 'Humans' rather than 'Econs' [@Thaler2008]. While discussion from @Thaler2008, @tversky1973availability and the others in Behavioural Economics has focused more on how the use of heuristics can cause departures from rationality, as we discussed [here](#quant-biases), this section looks at the impact of social norms on the efficiency of giving.^[Social norms promote giving to traditional non-EA causes and fundraisers, and responding to peer requests. --> crowding out? Norms may also suggest giving to causes like AMF is "weird".
]


\

**Asks** (Own category?)

Donation requests increase the propensity to give [@yorukHowResponsiveAre2009]. There is a conventional wisdom that "most donations occur in response to an ask".  If there are systematic asks for non-EA causes this may crowd out EG.

### Subjectivity in the charitable domain -

Evidence from @Berman2018

The idea that 'charity is a subjective decision' may constitute a social norm, a systemic factor inhibiting effective giving. We discuss this in more detail under [evaluation aversion](#subjectivity), particularly in subsection \@ref(subjectivity).


## Consider: inertia and obstacles to charities collecting, evaluating, and sharing impact information

<!--

Mulesky:

Even international health and humanitarian charities recognized as being unusually transparent keep details about their cost-effectiveness confidential. For example, in 2012 a representative from Médicines San Frontières told GiveWell that it regularly conducts program evaluations, but only a small number were publicly available. According to MSF, “sharing more program reports would take excessive time and resources” (GiveWell, 2012). Informal discussions with evaluation staff reveal that charities sometimes intentionally conceal the information from the public when the evaluations demonstrate the ineffectiveness of the organization’s program. For example, according to an interview with an evaluation consultant, Handicap International (HI) hired external evaluators to assess the impact of its antenatal care program for women in the Democratic Republic of the Congo three years into the project. The results “showed that the program hadn’t met any of its targets – it was a failed program with all the investment wasted.” After presenting the evaluation’s findings to staff in Brussels, the report was never disseminated beyond those in attendance, and “for all anyone knew it was a ‘success’...The message didn’t penetrate within the organization
-->


