-   *Summary for Gates foundation and Ideas42, draft composed by David
    > Reinstein; survey paper is with Nick Fitz, Ari Kagan, Robin Bergh,
    > and Jason Nemirow*

-   *\[Link to
    > "[[shareable]{.underline}](https://docs.google.com/document/d/1kRuO2edj8R2bZY-Tc2yw04ZcfEaY3pC38rOv0W0_rOM/edit)"
    > version\]*

**[Purpose and proposed outputs]{.underline}:** Our research,
communication, and impact program aims to provide practical methods to
increase the level and impact of *informed and intentional generosity*.
We are building a database of evidence on *what works*, focusing on
impact-driven donation behavior. We will assess, evaluate, and present
this through an interactive database, a collaborative wiki, and a
meta-analysis survey paper. Each of these will be carefully linked and
integrated. For example, the analysis and discussion in the survey paper
will be mirrored in the structure of the wiki, providing a platform for
discussion and updating. Each element of the surveyed evidence will be
provided as a database entry, cross-referencing relevant papers,
theories, use-cases, and available raw data. This *living resource* will
be able to quickly compile and disseminate the best available evidence
to users. Meta-analysis will be presented in the database and wiki, and
in a web app (e.g., R Shiny Rstudio). This will permit users to consider
alternate assumptions and methodological criteria, and to focus on
particular domains as relevant to their own practice. We aim to engage a
diverse user-base, including fundraisers, charities, academics, and
donors/philanthropists. Thus we will offer multiple formats (while
avoiding confusing overlap), allowing users to choose their preferred
level of technicality and detail.

*Partial and preliminary work can be found on the* [[Innovations in
Fundraising
wiki]{.underline}](http://innovationsinfundraising.org/doku.php?id=iifwiki:evidence_tools);
further resources are compiled in a shared relational database
(Airtable, described
[[here]{.underline}](https://www.dropbox.com/s/xefwbf9fjdny89m/airtable_database_overview.pdf?dl=0)).

1.  Key questions
    -------------

    1.  *Targeting and basic approach*

-   Who gives to effective charities, and can we predict who is likely
    > to be convinced to do so? How can we best target and persuade the
    > general population as well as high-ńet-worth individuals?

-   Is it productive to ask people to *shift* their giving towards more
    > impactful charities? If so, when and how? Underlying this: are
    > charities in competition and do people "rob Peter to pay Paul?"

*Psychology*

-   How can we present effectiveness information in a way that *works*,
    > without dampening emotional motivations to give? Can we avoid
    > self-interested "motivated reasoning" responses to this
    > information?

-   How can we reduce the *empathic distance* to people in low-income
    > countries and make those geographically-distant feel local?

-   How can we best apply well-tested emotional and behavioral
    > approaches (evidence-based fundraising tools like "gift exchange")
    > to *effective* charities. In applying these tools, what
    > "superpowers" and weaknesses do the most effective charities have?

-   How can we incorporate psychological and social *rewards for donors*
    > without overly sacrificing efficiency? What is the tradeoff
    > between promoting the purest, best-evidenced charities (e.g.,
    > GiveWell\'s list) and increasing the overall donation amounts?

-   Individual barriers to moving toward more effective giving may
    > include cognitive dissonance avoidance, cost-benefit aversion, and
    > opportunity-cost neglect; as well as common factual misconceptions
    > about international charities. Will de-biasing and correcting
    > misconceptions lead to more effective giving?

```{=html}
<!-- -->
```
-   

*Policy*

-   \- Will the tools that boost effective giving also increase support
    > for foreign aid and pro-poor policies?

-   \- What is the interaction between private giving, the level of
    > public funding for effective causes, and support for government
    > policies, and how can we boost the *net* public and private
    > impact?

    1.  A program for future work and for evaluating previous work
        ----------------------------------------------------------

```{=html}
<!-- -->
```
-   [Build platforms]{.underline} to observe relevant giving behavior
    > and run experiments to understand the impact of approaches across
    > several contexts

-   [Open Science Framework]{.underline}: Maintain research integrity,
    > collaboration and data-sharing, enabling re-analysis and
    > meta-analysis

-   [Robust and validated evidence]{.underline}: This includes
    > pre-registration and pre-analysis plans, experimentation and
    > independent replication across a range of relevant environment and
    > frames

-   [Present research for *users* in an effective way, using modern
    > information systems]{.underline}. Avoid \"old-school\" academic
    > journal presentation formats and \"frozen PDFs\" in favor of
    > living, continually-validated and re-assessed content. Open access
    > in a web framework.

-   [Collaboration]{.underline} with and among relevant
    > charities/fundraisers (e.g., International Fundraising Leadership
    > Forum)

-   Use wiki and other collaboration tools to organize open
    > communication and sharing

    -   of research results and insights, data, and methods,

    -   of informal (non-academic, non-systematic) trials and
        > experiences, and

    -   of critical insider knowledge and intuition

User stories: Who will use this and how?
========================================

1.  [Effective charities, their fundraisers, and groups of these
    > organizations]{.underline} (e.g., the
    > [[IFCL]{.underline}](http://www.fundraisers.fr/sites/default/files/4/IFL-Forum-presentation-at-IFC-2014_0.pdf))
    > will use this directly to increase their support-base, their
    > appeal, and their income. Evidence will be presented in
    > interactive and accessible ways, including more and less technical
    > presentations, allowing users to select a tailored analysis. We
    > will provide personal support to qualified effective charities.

2.  [Government policymakers]{.underline}: in enabling and enhancing
    > effective private giving, and providing public programs that are
    > compatible with this.

```{=html}
<!-- -->
```
3.  [Foundations]{.underline}: in targeting and communicating
    > interventions, considering interactions and feedback on the wider
    > society of givers

4.  [Advocates and activists]{.underline} for globally sympathetic and
    > pro-poor policies; as research is likely to unlock both factors
    > that encourage effective giving and factors that drive
    > cross-cultural sympathy, empathy, and action

5.  [Academic, professional, and applied researchers]{.underline}
    > interested in this area (both \"effective charitable giving\"
    > directly, and as an input into understanding human behavior). *Our
    > project will encourage and foster future work by\...*

    -   providing an accessible "evidence baseline": a shared database
        > of raw and meta-data,

    -   providing collaborative tools and platforms to facilitate
        > further analysis (e.g., working with e-commerce and social
        > fundraising sites to establish a continuous opportunity to
        > test charitable messaging in a stable context),

    -   building an interactive, global community of researchers and
        > practitioners, and

    -   providing a pathway to disseminate results to users and measure
        > a clear practical impact, and

    -   building tools and a framework to enable to a clear and
        > efficient process for evaluating and funding to evaluate and
        > disperse grants to fund promising research, following the
        > principles of open science.

The existing team and resources
===============================

**Principal investigator:** Dr. David Reinstein, Dept. of Economics,
University of Exeter

**Co-authors**

Dr. Nick Fitz (Psychology), Center for Advanced Hindsight, Duke
University

Ari Kagan, Center for Advanced Hindsight, Duke University

**Support and guidance (past, current, and promised) from:**

-   Dr. Paul Smeets (Sustainable Finance, University of Maastricht)

-   Dr. Lucius Caviola, Dept. of Psychology, University of Oxford

-   Dr. Robin Bergh, Sidanius lab, Harvard

-   Dr. Mark Kelson, Statistics and Data Science, University of Exeter

-   Dr. Ekaterina (Katja) Abramova (Cognitive Science, web developer)

-   Omar Parbhoo, Ideas42 and BHub

-   The Charity Science Foundation

-   Giving for Impact (Contact: Vera Scholermich)

-   The Life You Can Save/Giving Games (Contact: Jon Behar)

-   The Centre for Effective Altruism (Oxford; Contact: George Howlett)

```{=html}
<!-- -->
```
-   

Seeking support from: BITSS for meta-analysis projects, and from
X-Econ.org for data sharing

Further key issues
==================

[Combining and weighing information from different domains, with
different approaches, etc.]{.underline}

*Discussion moved to IIF page
[[HERE]{.underline}](http://innovationsinfundraising.org/doku.php?id=tools:meta-analysis_approach)*

**Omar**

Need to focus on how this interplays with the broader body of research,
how this can bind a very fragmented industry.

What we have shown doesn't make it clear... connect the dots more
explicitly. ... what does it mean for how learnings are disseminated,
how these are adopted.

Show

"Network for good" ...

Lilly institute

A charity doesn't have the expertise to differentiate rigorous and
soft/anecdotal evidence. Gates, how can they score the different types
of evidence?

and

Should ask people about use cases and what would be most useful to
users.

Ask Laura which practitioners to contact. Laura is the first stepping
stone to a chain of command that is relevant.

Ideas42 \-- expanding in-field testing; provide more insights that feed
into the wiki; helpful aggregators

Evaluation metrics looks confusing

Categorisations \-- legend for what these are, explain these better!

### Notes on meeting with Laura Tomasko, Gates Foundation

Laura is fairly new in this role (6 months). Gates Foundation has a
"Team" of 1.5 in DC; **Victoria Vrana** (sp) and ½ of Laura on "**Giving
by All.**" It might be good to speak directly with Victoria as well.

[Main takeaways]{.underline}

Laura essentially advised us to go through the Ideas42 and work with
Omar. She seemed very amenable to any cooperation that we could work out
with Ideas42, with their existing funding, or even perhaps with some new
grant. We should ask Omar whom has he been talking to and whom have they
been engaging in setting up and designing these experiments? Are there
projects we should collaborate on. Ask Ideas42 "what are they missing
that would help them with the next phase'?

They seem to have some academic partners as well (Indiana and Stanford),
which we might chase up; probably best to talk to these groups to
consider how we might carve out a niche for ourselves.

She suggested there might be a potential area for growth in the "channel
strategy".. they may be willing to add an additional channel.

Laura sees a difference between the gates "Giving by All" project
targeted at "donors" and our project targeted at fundraisers, but I
think these are essentially the same. She speaks of 'research'
distinctly from 'experiments'; their experiments are being coordinated
by Ideas42. I tried to convince her that research and experiments are
interconnected. I also pushed a little bit on 'how do they know they are
doing the best experiments ... without having an open dialogue and open
science framework with the academic community.

[The Gates (sub)project: "Giving by all" (GbA)]{.underline}

This project aims to get donors giving in a more *intentional* and
*informed* way (not just giving more, but also not exactly pushing them
to more effective charities). This has been a 'learning initiative' for
several years, but they have no official go-ahead about continuation in
this low-key status or ramping it up. This project has not been brought
to press. This is one of a few projects by their "philanthropic
partnership team."

*Giving by All; three buckets*

i\. **Data and research** (who/where/why) (**ideas42+Stanford+Indiana**)

ii\. **Bottlenecks and solutions; designing experiments testing these**;
through **Workplace** giving, **Online giving** **platforms,
Donor-advised funds, Social giving circles**

iii\. Once they have run an experiment in the second bucket, they think
about how to 'take this to market.'

Where possible, they want to support new features on existing platforms,
rather than new platforms

GbA Academic contacts:

-   Stanford university \-- Nadia Roumani \-- HNW individuals and
    > results-giving; **Effective Philanthropy Lab**, Pacs centre

-   Nadia is working on HNW and the larger group

-   Also, **IUPIU**, Lily School of Philanthropy, Women's Philanthropy
    > Institute, SPI?

```{=html}
<!-- -->
```
-   Ideas42 as primary research partner; also helping to run the
    > experiments

["Philanthropic partnership team", other information on what they have
done and do]{.underline}

\... **goal is to increase informed/intentional giving across the
world**.

**Focus on high-end (e.g., Gates-Buffett Giving Pledge)**

Laura: Also looks at "**policies and systems**" ... tax etc...

'Data and insights' is more on the **'quality' of giving; opportunity
for individual donors to become more informed**

Also have a London office

Globally focused on Middle East, China, and India ... culture around
giving. Policy incentives miht enhance a culture of giving.

Colleague in India

Mission measurement and the 'Impact genome project'

"Stay Classy" org

**Guidestar is a grantee in data and insights**; considering working
with **"Global Giving"** **badges**

... **Supported Giving Tuesday**, experimented with impact data.

*Blockchain technology* ... new opportunities to get information about
outcomes?

Alice (UK-based ..., using blockchain tech to get donations based on
outcomes... social impact bond paper successworld)

Laura is not the program officer for grants Indiana (Victoria is?)

Omar \-- Stanford pilots; give list (Nadia)

Have run match donation experiments on dDonors Choose (matching
donations)

Funded a "Data Dive"

[Her comments/questions on our project]{.underline}

'How do you differ from the groups like the Association of fundraising
professionals?' I explained that we are focused on building a strong
evidence base, working with academics in a collaborative way, and we are
particularly focused on *effective* giving.

I asked her for comments on innovationsinfundraising.org. She suggested
it was focused on fundraisers rather than donors (as they are). I made
the point that these are in essence equivalent. I also suggested we
could refocus a bit but she argued we should keep doing what we are
doing as we know what is needed. She seemed happy with the aspects of
the site she had seen, and had no particular comments. She thought it
was very interesting to look at *channels* of giving.

Kelson 
======

"lumper or a splitter"

'triangulation' (i.e., convergent validation)\... from studies that
don't share sources of error

have people done correlational studies \*between\* hypothetical and
incentivised

IN synthesizing this ... estimate the \*size\* of the effect and the
CI... not the p-value

"Stat-checks"

Clinical trials, standard reporting formats

10 million grant for a bio-medical lab to be named after a power
couple... make a business case for the university alumni fundraising...
see if we could max that potential

Need some 'here are the things we find most effective as an outcome of
this page'

Could be an input into running a massive trial

Need an 'information specialist' ... search strategies: topic experts,
behavioral strategists, statistical expertise, (patient world: 'a
donor'?)

GCRF possibility 
================

I\'m working on an interdisciplinary project \"Increasing effective
charitable giving: The puzzle, what we know, what we need to know next\"
with a number of psychologists/social scientists (at Harvard, Duke, and
other places mainly in the US). This will involve a review paper aimed
to provide a framework, jumping-off point, and baseline to foment
further research in this area (in Economics, Psychology, Data Science
and elsewhere). It also involves a meta-analysis project carefully
consolidating evidence. The research will directly link with and be used
engagement activities at innovationsinfundraising.org and beyond.

The GCRF criteria include:

\"Any GCRF proposal must make it clear that its primary purpose is to
promote the economic

development and welfare of a developing country or countries. Applicants
should:\... Seek to investigate a specific problem or seek a specific
outcome which will have an impact on a developing country or countries
on the DAC list\"

My thought is that the \'problem\' is (roughly):

\...the *barriers* (to individuals in wealthy countries)
caring/giving/supporting the needy in developing countries, which limits
effective charitable giving to help them (and also affects support for
government policies.)

By understanding these barriers carefully and empirically, and
disseminating this information (to charities and NGOs, activists, etc)
we can formulate potential solutions leading to more effective giving
(and support for pro-poor international policies), greatly benefitting
poor individuals in developing countries.

I sincerely believe that this is a \'first order\' thing that will make
a huge difference to LDC\'s. However, I\'m wondering whether it will be
considered to fit within the category in a precise sense.

Leverhulme app possibility 
==========================

see: [[David Reinstein - Leverhulme International Academic Fellowship
notes]{.underline}](https://docs.google.com/document/d/16ARHaErBemIpeTJdf2RGmBRIuXFspHHXiv2WTSd11wA/edit#heading=h.h6qynffar6qs)
